stages:

  inspect_tools:
    foreach:
      utilities:
        name: utilities
        specification: 9ec8df2a1ad7633ed0893527ca1c8c4f56426ab868a0adccea366a9fbf799898
      arboreto:
        name: arboreto
        specification: 540b9a053e4d862bfab972735d1d62af04485c186cf5735e98748ef5b5f8b27f
      NetworkInferenceJl:
        name: NetworkInference.jl
        specification: 3e491ce8057710cc2f0cf020b178f6315889e1b19357716b5f0da301475f9098
      Rmultitool:
        name: R-multitool
        specification: adc703754189748fa75be2a4ec9f317f39409cfaf08eee163d7f8f59c6b511d1
    do:
      cmd:
      - mkdir -p results/tooling
      - singularity run --app manifest toolbox/bin/${item.name}.sif
        >results/tooling/${item.name}.manifest
      - singularity run --app specification toolbox/bin/${item.name}.sif
        ${item.specification}
        >results/tooling/${item.name}.specification
      deps:
      - toolbox/bin/${item.name}.sif
      outs:
      - results/tooling/${item.name}.manifest
      - results/tooling/${item.name}.specification

  acquire_data:
    cmd:
    - mkdir -p results
    - singularity exec toolbox/bin/utilities.sif
      wget -O results/raw-inputs.zip https://ndownloader.figshare.com/files/26052149
    deps:
      - results/tooling/utilities.specification
      - https://ndownloader.figshare.com/files/26052149
    outs:
      - results/raw-inputs.zip
  extract_Yang_data:
    cmd: singularity exec toolbox/bin/utilities.sif sh src/extract_data.sh
      results/raw-inputs.zip
      "noise_GRN_share/bulk_Yang/*"
      results/raw/Yang
    deps:
    - results/raw-inputs.zip
    - results/tooling/utilities.specification
    outs:
    - results/raw/Yang
  extract_Cuomo_data:
    cmd: singularity exec toolbox/bin/utilities.sif sh src/extract_data.sh
      results/raw-inputs.zip
      "noise_GRN_share/SC_Cuomo/*"
      results/raw/Cuomo
    deps:
    - results/raw-inputs.zip
    - results/tooling/utilities.specification
    outs:
    - results/raw/Cuomo
  clean_Yang_data:
    cmd: singularity exec toolbox/bin/utilities.sif sh src/clean_Yang.sh
      results/raw/Yang
      results/clean/Yang
    deps:
    - results/raw/Yang
    - results/tooling/utilities.specification
    - src/clean_Yang.sh
    outs:
    - results/clean/Yang
  clean_Cuomo_data:
    cmd: singularity exec toolbox/bin/utilities.sif sh src/clean_Cuomo.sh
      results/raw/Cuomo
      results/clean/Cuomo
    deps:
    - results/raw/Cuomo
    - results/tooling/utilities.specification
    - src/clean_Cuomo.sh
    outs:
    - results/clean/Cuomo
  denoise_Yang_data:
    cmd: singularity exec toolbox/bin/R-multitool.sif sh src/denoise.sh
      results/clean/Yang
      counts_raw.csv
      results/denoised/Yang
      logs/denoised/Yang
    deps:
      - results/clean/Yang
      - results/tooling/R-multitool.specification
      - src/denoise.sh
      - src/denoise.R
    outs:
      - results/denoised/Yang
  denoise_Cuomo_data:
    cmd: singularity exec toolbox/bin/R-multitool.sif sh src/denoise.sh
      results/clean/Cuomo
      counts_raw_day2.csv
      results/denoised/Cuomo
      logs/denoised/Cuomo
    deps:
      - results/clean/Cuomo
      - results/tooling/R-multitool.specification
      - src/denoise.sh
      - src/denoise.R
    outs:
      - results/denoised/Cuomo
  slice_Yang_data:
    cmd: singularity exec toolbox/bin/utilities.sif sh src/slice.sh
      results/denoised/Yang
      results/sliced/Yang
    deps:
    - results/denoised/Yang
    - results/tooling/utilities.specification
    - src/slice.sh
    outs:
    - results/sliced/Yang
  fuse_Yang_data:
    cmd: singularity exec toolbox/bin/R-multitool.sif sh src/fuse_samples_foreach.sh
      results/denoised/Yang
      results/clean/Yang/samples.csv
      results/fused/Yang
    deps:
    - results/clean/Yang
    - results/denoised/Yang
    - results/tooling/R-multitool.specification
    - src/fuse_samples_foreach.sh
    - src/fuse_samples.R
    outs:
    - results/fused/Yang
  slice_Yang_fused_data:
    cmd: singularity exec toolbox/bin/utilities.sif sh src/slice.sh
      results/fused/Yang
      results/sliced_fused/Yang
    deps:
    - results/fused/Yang
    - results/tooling/utilities.specification
    - src/slice.sh
    outs:
    - results/sliced_fused/Yang
  slice_Cuomo_data:
    cmd: singularity exec toolbox/bin/utilities.sif sh src/slice.sh
      results/denoised/Cuomo
      results/sliced/Cuomo
    deps:
    - results/denoised/Cuomo
    - results/tooling/utilities.specification
    - src/slice.sh
    outs:
    - results/sliced/Cuomo

  infer:
    foreach:
      Yang/NetworkInference.jl/CLR:   { data: Yang,  tool: NetworkInference.jl, src: NetworkInference.jl, cmd: "julia src/inference/NetworkInference.jl/infer_network.jl CLR" }
      Yang/NetworkInference.jl/MI:    { data: Yang,  tool: NetworkInference.jl, src: NetworkInference.jl, cmd: "julia src/inference/NetworkInference.jl/infer_network.jl MI" }
      Yang/NetworkInference.jl/PIDC:  { data: Yang,  tool: NetworkInference.jl, src: NetworkInference.jl, cmd: "julia src/inference/NetworkInference.jl/infer_network.jl PIDC" }
      Yang/NetworkInference.jl/PUC:   { data: Yang,  tool: NetworkInference.jl, src: NetworkInference.jl, cmd: "julia src/inference/NetworkInference.jl/infer_network.jl PUC" }
      Yang/GENIE3-R:                  { data: Yang,  tool: R-multitool,         src: GENIE3-R,            cmd: "Rscript src/inference/GENIE3-R/infer_network.R" }
      Yang/LEAP:                      { data: Yang,  tool: R-multitool,         src: LEAP,                cmd: "Rscript src/inference/LEAP/infer_network.R" }
      Yang/GRNBoost2:                 { data: Yang,  tool: arboreto,            src: GRNBoost2,           cmd: "python src/inference/GRNBoost2/infer_network.py" }
      Cuomo/NetworkInference.jl/CLR:  { data: Cuomo, tool: NetworkInference.jl, src: NetworkInference.jl, cmd: "julia src/inference/NetworkInference.jl/infer_network.jl CLR" }
      Cuomo/NetworkInference.jl/MI:   { data: Cuomo, tool: NetworkInference.jl, src: NetworkInference.jl, cmd: "julia src/inference/NetworkInference.jl/infer_network.jl MI" }
      Cuomo/NetworkInference.jl/PIDC: { data: Cuomo, tool: NetworkInference.jl, src: NetworkInference.jl, cmd: "julia src/inference/NetworkInference.jl/infer_network.jl PIDC" }
      Cuomo/NetworkInference.jl/PUC:  { data: Cuomo, tool: NetworkInference.jl, src: NetworkInference.jl, cmd: "julia src/inference/NetworkInference.jl/infer_network.jl PUC" }
      Cuomo/GENIE3-R:                 { data: Cuomo, tool: R-multitool,         src: GENIE3-R,            cmd: "Rscript src/inference/GENIE3-R/infer_network.R" }
      Cuomo/GRNBoost2:                { data: Cuomo, tool: arboreto,            src: GRNBoost2,           cmd: "python src/inference/GRNBoost2/infer_network.py" }
    do:
      cmd: singularity exec toolbox/bin/${item.tool}.sif sh src/inference/infer_foreach_slice.sh
        results/sliced/${item.data}
        results/networks/${key}
        logs/networks/${key}
        ${item.cmd}
      deps:
      - results/sliced/${item.data}
      - results/tooling/${item.tool}.specification
      - src/inference/infer_foreach_slice.sh
      - src/inference/${item.src}
      outs:
      - results/networks/${key}

  analyze:
    foreach:
      Yang/NetworkInference.jl/CLR:   { loader: load_network_inference_jl_network.function.R }
      Yang/NetworkInference.jl/MI:    { loader: load_network_inference_jl_network.function.R }
      Yang/NetworkInference.jl/PIDC:  { loader: load_network_inference_jl_network.function.R }
      Yang/NetworkInference.jl/PUC:   { loader: load_network_inference_jl_network.function.R }
      Yang/GENIE3-R:                  { loader: load_genie3r_network.function.R }
      Yang/LEAP:                      { loader: load_leap_network.function.R }
      Yang/GRNBoost2:                 { loader: load_grnboost2_network.function.R }
      Cuomo/NetworkInference.jl/CLR:  { loader: load_network_inference_jl_network.function.R }
      Cuomo/NetworkInference.jl/MI:   { loader: load_network_inference_jl_network.function.R }
      Cuomo/NetworkInference.jl/PIDC: { loader: load_network_inference_jl_network.function.R }
      Cuomo/NetworkInference.jl/PUC:  { loader: load_network_inference_jl_network.function.R }
      Cuomo/GENIE3-R:                 { loader: load_genie3r_network.function.R }
      Cuomo/GRNBoost2:                { loader: load_grnboost2_network.function.R }
    do:
      cmd: singularity exec toolbox/bin/R-multitool.sif sh src/analysis/analyze_foreach_slice.sh
        results/networks/${key}
        results/analysis/${key}
        logs/analysis/${key}
        Rscript src/analysis/analyze_for_network_variants.R src/analysis/data_variants.csv src/analysis/${item.loader} png
      deps:
      - results/networks/${key}
      - results/tooling/R-multitool.specification
      - src/analysis/analyze_foreach_slice.sh
      - src/analysis/analyze_for_network_variants.R
      - src/analysis/data_variants.csv
      - src/analysis/${item.loader}
      outs:
      - results/analysis/${key}
