stages:
  acquire_Yang_data:
    cmd: mkdir -p results/Yang/raw && cp inputs/bulk_Yang-20210102T132322Z-001.zip results/Yang/raw/Yang.zip
    deps:
    - inputs/bulk_Yang-20201211T162105Z-001.zip
    outs:
    - results/Yang/raw/Yang.zip
  acquire_Cuomo_data:
    cmd: mkdir -p results/Cuomo/raw && cp inputs/SC_Cuomo-20210102T132349Z-001.zip results/Cuomo/raw/Cuomo.zip
    deps:
    - inputs/SC_Cuomo-20201211T162156Z-001.zip
    outs:
    - results/Cuomo/raw/Cuomo.zip
  extract_Yang_data:
    cmd: singularity run toolbox/bin/utilities.sif unzip results/Yang/raw/Yang.zip -d results/Yang/raw
    deps:
    - results/Yang/raw/Yang.zip
    - toolbox/bin/utilities.tag
    outs:
    - results/Yang/raw/bulk_Yang
  extract_Cuomo_data:
    cmd: singularity run toolbox/bin/utilities.sif unzip results/Cuomo/raw/Cuomo.zip -d results/Cuomo/raw
    deps:
    - results/Cuomo/raw/Cuomo.zip
    - toolbox/bin/utilities.tag
    outs:
    - results/Cuomo/raw/SC_Cuomo
