stages:
  inspect_utilities:
    cmd: mkdir -p results/tooling && singularity run --app specification toolbox/bin/utilities.sif
      >results/tooling/utilities.specification
    deps:
    - toolbox/bin/utilities.sif
    outs:
    - results/tooling/utilities.specification
  inspect_arboreto:
    cmd: mkdir -p results/tooling && singularity run --app specification toolbox/bin/arboreto.sif
      >results/tooling/arboreto.specification
    deps:
    - toolbox/bin/arboreto.sif
    outs:
    - results/tooling/arboreto.specification
  inspect_NetworkInferenceJl:
    cmd: mkdir -p results/tooling && singularity run --app specification toolbox/bin/NetworkInference.jl.sif
      >results/tooling/NetworkInference.jl.specification
    deps:
    - toolbox/bin/NetworkInference.jl.sif
    outs:
    - results/tooling/NetworkInference.jl.specification
  inspect_Rmultitool:
    cmd: mkdir -p results/tooling && singularity run --app specification toolbox/bin/R-multitool.sif
      >results/tooling/R-multitool.specification
    deps:
    - toolbox/bin/R-multitool.sif
    outs:
    - results/tooling/R-multitool.specification
  acquire_Yang_data:
    cmd: mkdir -p results/Yang/raw && cp inputs/bulk_Yang-20210102T132322Z-001.zip
      results/Yang/raw/Yang.zip
    deps:
    - inputs/bulk_Yang-20201211T162105Z-001.zip
    outs:
    - results/Yang/raw/Yang.zip
  acquire_Cuomo_data:
    cmd: mkdir -p results/Cuomo/raw && cp inputs/SC_Cuomo-20210102T132349Z-001.zip
      results/Cuomo/raw/Cuomo.zip
    deps:
    - inputs/SC_Cuomo-20201211T162156Z-001.zip
    outs:
    - results/Cuomo/raw/Cuomo.zip
  extract_Yang_data:
    cmd: singularity run toolbox/bin/utilities.sif unzip results/Yang/raw/Yang.zip
      -d results/Yang/raw
    deps:
    - results/Yang/raw/Yang.zip
    - results/tooling/utilities.specification
    outs:
    - results/Yang/raw/bulk_Yang
  extract_Cuomo_data:
    cmd: singularity run toolbox/bin/utilities.sif unzip results/Cuomo/raw/Cuomo.zip
      -d results/Cuomo/raw
    deps:
    - results/Cuomo/raw/Cuomo.zip
    - results/tooling/utilities.specification
    outs:
    - results/Cuomo/raw/SC_Cuomo
  clean_Yang_data:
    cmd: singularity run toolbox/bin/utilities.sif src/clean_Yang.sh results/Yang/raw/bulk_Yang
      results/Yang/clean
    deps:
    - results/Yang/raw/bulk_Yang
    - results/tooling/utilities.specification
    - src/clean_Yang.sh
    outs:
    - results/Yang/clean
  clean_Cuomo_data:
    cmd: singularity run toolbox/bin/utilities.sif src/clean_Cuomo.sh results/Cuomo/raw/SC_Cuomo
      results/Cuomo/clean
    deps:
    - results/Cuomo/raw/SC_Cuomo
    - results/tooling/utilities.specification
    - src/clean_Cuomo.sh
    outs:
    - results/Cuomo/clean
  slice_Yang_data:
    cmd: singularity run toolbox/bin/utilities.sif src/slice.sh results/Yang/clean
      results/Yang/sliced
    deps:
    - results/Yang/clean
    - results/tooling/utilities.specification
    - src/slice.sh
    outs:
    - results/Yang/sliced
  slice_Cuomo_data:
    cmd: singularity run toolbox/bin/utilities.sif src/slice.sh results/Cuomo/clean
      results/Cuomo/sliced
    deps:
    - results/Cuomo/clean
    - results/tooling/utilities.specification
    - src/slice.sh
    outs:
    - results/Cuomo/sliced
  infer_Yang_NetworkInferenceJl_CLR:
    cmd: singularity exec toolbox/bin/NetworkInference.jl.sif sh src/infer_foreach_slice.sh
      results/Yang/sliced
      results/Yang/networks/NetworkInference.jl/CLR
      logs/Yang/networks/NetworkInference.jl/CLR
      julia src/NetworkInference.jl/infer_network.jl CLR
    deps:
    - results/Yang/sliced
    - results/tooling/NetworkInference.jl.specification
    - src/infer_foreach_slice.sh
    - src/NetworkInference.jl
    outs:
    - results/Yang/networks/NetworkInference.jl/CLR
  infer_Cuomo_NetworkInferenceJl_CLR:
    cmd: singularity exec toolbox/bin/NetworkInference.jl.sif sh src/infer_foreach_slice.sh
      results/Cuomo/sliced
      results/Cuomo/networks/NetworkInference.jl/CLR
      logs/Cuomo/networks/NetworkInference.jl/CLR
      julia src/NetworkInference.jl/infer_network.jl CLR
    deps:
    - results/Cuomo/sliced
    - results/tooling/NetworkInference.jl.specification
    - src/infer_foreach_slice.sh
    - src/NetworkInference.jl
    outs:
    - results/Cuomo/networks/NetworkInference.jl/CLR
  infer_Yang_NetworkInferenceJl_MI:
    cmd: singularity exec toolbox/bin/NetworkInference.jl.sif sh src/infer_foreach_slice.sh
      results/Yang/sliced
      results/Yang/networks/NetworkInference.jl/MI
      logs/Yang/networks/NetworkInference.jl/MI
      julia src/NetworkInference.jl/infer_network.jl MI
    deps:
    - results/Yang/sliced
    - results/tooling/NetworkInference.jl.specification
    - src/infer_foreach_slice.sh
    - src/NetworkInference.jl
    outs:
    - results/Yang/networks/NetworkInference.jl/MI
  infer_Cuomo_NetworkInferenceJl_MI:
    cmd: singularity exec toolbox/bin/NetworkInference.jl.sif sh src/infer_foreach_slice.sh
      results/Cuomo/sliced
      results/Cuomo/networks/NetworkInference.jl/MI
      logs/Cuomo/networks/NetworkInference.jl/MI
      julia src/NetworkInference.jl/infer_network.jl MI
    deps:
    - results/Cuomo/sliced
    - results/tooling/NetworkInference.jl.specification
    - src/infer_foreach_slice.sh
    - src/NetworkInference.jl
    outs:
    - results/Cuomo/networks/NetworkInference.jl/MI
  infer_Yang_NetworkInferenceJl_PIDC:
    cmd: singularity exec toolbox/bin/NetworkInference.jl.sif sh src/infer_foreach_slice.sh
      results/Yang/sliced
      results/Yang/networks/NetworkInference.jl/PIDC
      logs/Yang/networks/NetworkInference.jl/PIDC
      julia src/NetworkInference.jl/infer_network.jl PIDC
    deps:
    - results/Yang/sliced
    - results/tooling/NetworkInference.jl.specification
    - src/infer_foreach_slice.sh
    - src/NetworkInference.jl
    outs:
    - results/Yang/networks/NetworkInference.jl/PIDC
  infer_Cuomo_NetworkInferenceJl_PIDC:
    cmd: singularity exec toolbox/bin/NetworkInference.jl.sif sh src/infer_foreach_slice.sh
      results/Cuomo/sliced
      results/Cuomo/networks/NetworkInference.jl/PIDC
      logs/Cuomo/networks/NetworkInference.jl/PIDC
      julia src/NetworkInference.jl/infer_network.jl PIDC
    deps:
    - results/Cuomo/sliced
    - results/tooling/NetworkInference.jl.specification
    - src/infer_foreach_slice.sh
    - src/NetworkInference.jl
    outs:
    - results/Cuomo/networks/NetworkInference.jl/PIDC
  infer_Yang_NetworkInferenceJl_PUC:
    cmd: singularity exec toolbox/bin/NetworkInference.jl.sif sh src/infer_foreach_slice.sh
      results/Yang/sliced
      results/Yang/networks/NetworkInference.jl/PUC
      logs/Yang/networks/NetworkInference.jl/PUC
      julia src/NetworkInference.jl/infer_network.jl PUC
    deps:
    - results/Yang/sliced
    - results/tooling/NetworkInference.jl.specification
    - src/infer_foreach_slice.sh
    - src/NetworkInference.jl
    outs:
    - results/Yang/networks/NetworkInference.jl/PUC
  infer_Cuomo_NetworkInferenceJl_PUC:
    cmd: singularity exec toolbox/bin/NetworkInference.jl.sif sh src/infer_foreach_slice.sh
      results/Cuomo/sliced
      results/Cuomo/networks/NetworkInference.jl/PUC
      logs/Cuomo/networks/NetworkInference.jl/PUC
      julia src/NetworkInference.jl/infer_network.jl PUC
    deps:
    - results/Cuomo/sliced
    - results/tooling/NetworkInference.jl.specification
    - src/infer_foreach_slice.sh
    - src/NetworkInference.jl
    outs:
    - results/Cuomo/networks/NetworkInference.jl/PUC
  infer_Yang_GENIE3R:
    cmd: singularity exec toolbox/bin/R-multitool.sif sh src/infer_foreach_slice.sh
      results/Yang/sliced
      results/Yang/networks/GENIE3-R
      logs/Yang/networks/GENIE3-R
      Rscript src/GENIE3-R/infer_network.R
    deps:
    - results/Yang/sliced
    - results/tooling/R-multitool.specification
    - src/infer_foreach_slice.sh
    - src/GENIE3-R
    outs:
    - results/Yang/networks/GENIE3-R
  infer_Cuomo_GENIE3R:
    cmd: singularity exec toolbox/bin/R-multitool.sif sh src/infer_foreach_slice.sh
      results/Cuomo/sliced
      results/Cuomo/networks/GENIE3-R
      logs/Cuomo/networks/GENIE3-R
      Rscript src/GENIE3-R/infer_network.R
    deps:
    - results/Cuomo/sliced
    - results/tooling/R-multitool.specification
    - src/infer_foreach_slice.sh
    - src/GENIE3-R
    outs:
    - results/Cuomo/networks/GENIE3-R
  infer_Yang_LEAP:
    cmd: singularity exec toolbox/bin/R-multitool.sif sh src/infer_foreach_slice.sh
      results/Yang/sliced
      results/Yang/networks/LEAP
      logs/Yang/networks/LEAP
      Rscript src/LEAP/infer_network.R
    deps:
    - results/Yang/sliced
    - results/tooling/R-multitool.specification
    - src/infer_foreach_slice.sh
    - src/LEAP
    outs:
    - results/Yang/networks/LEAP
  infer_Cuomo_LEAP:
    cmd: singularity exec toolbox/bin/R-multitool.sif sh src/infer_foreach_slice.sh
      results/Cuomo/sliced
      results/Cuomo/networks/LEAP
      logs/Cuomo/networks/LEAP
      Rscript src/LEAP/infer_network.R
    deps:
    - results/Cuomo/sliced
    - results/tooling/R-multitool.specification
    - src/infer_foreach_slice.sh
    - src/LEAP
    outs:
    - results/Cuomo/networks/LEAP
  infer_Yang_GRNBoost2:
    cmd: singularity exec toolbox/bin/arboreto.sif sh src/infer_foreach_slice.sh
      results/Yang/sliced
      results/Yang/networks/GRNBoost2
      logs/Yang/networks/GRNBoost2
      python src/GRNBoost2/infer_network.py
    deps:
    - results/Yang/sliced
    - results/tooling/arboreto.specification
    - src/infer_foreach_slice.sh
    - src/GRNBoost2
    outs:
    - results/Yang/networks/GRNBoost2
  infer_Cuomo_GRNBoost2:
    cmd: singularity exec toolbox/bin/arboreto.sif sh src/infer_foreach_slice.sh
      results/Cuomo/sliced
      results/Cuomo/networks/GRNBoost2
      logs/Cuomo/networks/GRNBoost2
      python src/GRNBoost2/infer_network.py
    deps:
    - results/Cuomo/sliced
    - results/tooling/arboreto.specification
    - src/infer_foreach_slice.sh
    - src/GRNBoost2
    outs:
    - results/Cuomo/networks/GRNBoost2
