stages:
  acquire_Yang_data:
    cmd: mkdir -p results/Yang/raw && cp inputs/bulk_Yang-20210102T132322Z-001.zip
      results/Yang/raw/Yang.zip
    deps:
    - inputs/bulk_Yang-20201211T162105Z-001.zip
    outs:
    - results/Yang/raw/Yang.zip
  acquire_Cuomo_data:
    cmd: mkdir -p results/Cuomo/raw && cp inputs/SC_Cuomo-20210102T132349Z-001.zip
      results/Cuomo/raw/Cuomo.zip
    deps:
    - inputs/SC_Cuomo-20201211T162156Z-001.zip
    outs:
    - results/Cuomo/raw/Cuomo.zip
  extract_Yang_data:
    cmd: singularity run toolbox/bin/utilities.sif unzip results/Yang/raw/Yang.zip
      -d results/Yang/raw
    deps:
    - results/Yang/raw/Yang.zip
    - toolbox/bin/utilities.tag
    outs:
    - results/Yang/raw/bulk_Yang
  extract_Cuomo_data:
    cmd: singularity run toolbox/bin/utilities.sif unzip results/Cuomo/raw/Cuomo.zip
      -d results/Cuomo/raw
    deps:
    - results/Cuomo/raw/Cuomo.zip
    - toolbox/bin/utilities.tag
    outs:
    - results/Cuomo/raw/SC_Cuomo
  clean_Yang_data:
    cmd: singularity run toolbox/bin/utilities.sif src/clean_Yang.sh results/Yang/raw/bulk_Yang
      results/Yang/clean
    deps:
    - results/Yang/raw/bulk_Yang
    - src/clean_Yang.sh
    - toolbox/bin/utilities.tag
    outs:
    - results/Yang/clean
  clean_Cuomo_data:
    cmd: singularity run toolbox/bin/utilities.sif src/clean_Cuomo.sh results/Cuomo/raw/SC_Cuomo
      results/Cuomo/clean
    deps:
    - results/Cuomo/raw/SC_Cuomo
    - src/clean_Cuomo.sh
    - toolbox/bin/utilities.tag
    outs:
    - results/Cuomo/clean
  slice_Yang_data:
    cmd: singularity run toolbox/bin/utilities.sif src/slice.sh results/Yang/clean
      results/Yang/sliced
    deps:
    - results/Yang/clean
    - src/slice.sh
    - toolbox/bin/utilities.tag
    outs:
    - results/Yang/sliced
  slice_Cuomo_data:
    cmd: singularity run toolbox/bin/utilities.sif src/slice.sh results/Cuomo/clean
      results/Cuomo/sliced
    deps:
    - results/Cuomo/clean
    - src/slice.sh
    - toolbox/bin/utilities.tag
    outs:
    - results/Cuomo/sliced
  infer_Yang_NetworkInferenceJl_CLR:
    cmd: singularity exec toolbox/bin/PIDC.sif sh src/NetworkInference.jl/infer_networks.sh
      CLR results/Yang/sliced results/Yang/networks/NetworkInference.jl/CLR
    deps:
    - results/Yang/sliced
    - src/NetworkInference.jl
    - toolbox/bin/PIDC.tag
    outs:
    - results/Yang/networks/NetworkInference.jl/CLR
  infer_Cuomo_NetworkInferenceJl_CLR:
    cmd: singularity exec toolbox/bin/PIDC.sif sh src/NetworkInference.jl/infer_networks.sh
      CLR results/Cuomo/sliced results/Cuomo/networks/NetworkInference.jl/CLR
    deps:
    - results/Cuomo/sliced
    - src/NetworkInference.jl
    - toolbox/bin/PIDC.tag
    outs:
    - results/Cuomo/networks/NetworkInference.jl/CLR
  infer_Yang_NetworkInferenceJl_MI:
    cmd: singularity exec toolbox/bin/PIDC.sif sh src/NetworkInference.jl/infer_networks.sh
      MI results/Yang/sliced results/Yang/networks/NetworkInference.jl/MI
    deps:
    - results/Yang/sliced
    - src/NetworkInference.jl
    - toolbox/bin/PIDC.tag
    outs:
    - results/Yang/networks/NetworkInference.jl/MI
  infer_Cuomo_NetworkInferenceJl_MI:
    cmd: singularity exec toolbox/bin/PIDC.sif sh src/NetworkInference.jl/infer_networks.sh
      MI results/Cuomo/sliced results/Cuomo/networks/NetworkInference.jl/MI
    deps:
    - results/Cuomo/sliced
    - src/NetworkInference.jl
    - toolbox/bin/PIDC.tag
    outs:
    - results/Cuomo/networks/NetworkInference.jl/MI
  infer_Yang_NetworkInferenceJl_PIDC:
    cmd: singularity exec toolbox/bin/PIDC.sif sh src/NetworkInference.jl/infer_networks.sh
      PIDC results/Yang/sliced results/Yang/networks/NetworkInference.jl/PIDC
    deps:
    - results/Yang/sliced
    - src/NetworkInference.jl
    - toolbox/bin/PIDC.tag
    outs:
    - results/Yang/networks/NetworkInference.jl/PIDC
  infer_Cuomo_NetworkInferenceJl_PIDC:
    cmd: singularity exec toolbox/bin/PIDC.sif sh src/NetworkInference.jl/infer_networks.sh
      PIDC results/Cuomo/sliced results/Cuomo/networks/NetworkInference.jl/PIDC
    deps:
    - results/Cuomo/sliced
    - src/NetworkInference.jl
    - toolbox/bin/PIDC.tag
    outs:
    - results/Cuomo/networks/NetworkInference.jl/PIDC
  infer_Yang_NetworkInferenceJl_PUC:
    cmd: singularity exec toolbox/bin/PIDC.sif sh src/NetworkInference.jl/infer_networks.sh
      PUC results/Yang/sliced results/Yang/networks/NetworkInference.jl/PUC
    deps:
    - results/Yang/sliced
    - src/NetworkInference.jl
    - toolbox/bin/PIDC.tag
    outs:
    - results/Yang/networks/NetworkInference.jl/PUC
  infer_Cuomo_NetworkInferenceJl_PUC:
    cmd: singularity exec toolbox/bin/PIDC.sif sh src/NetworkInference.jl/infer_networks.sh
      PUC results/Cuomo/sliced results/Cuomo/networks/NetworkInference.jl/PUC
    deps:
    - results/Cuomo/sliced
    - src/NetworkInference.jl
    - toolbox/bin/PIDC.tag
    outs:
    - results/Cuomo/networks/NetworkInference.jl/PUC
